### ISSUE TITLE
auth token invalid

### ISSUE THREAD

**Issue by ngam** [conda-forge/kaggle-feedstock#25]
@conda-forge/core, see https://github.com/conda-forge/kaggle-feedstock/runs/4564200556

any help?

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by beckermr** [comment]
Rerender the feedstock pls.

**Comment by ngam** [comment]
Like a in a new pr or is there a way to do that in an issue?
